@server =https://laww25-didactic-couscous-9pgv9qpqrr7hp5rr-8080.preview.app.github.dev

GET {{server}}/categorias
###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Instrumentos de Cuerda"}
